### Post multiple customers
POST http://127.0.0.1:8080/customers
Content-Type: application/json

[
  {
    "name": "Test customer1"
  },
  {
    "name": "Test customer2"
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Post single customer
POST http://127.0.0.1:8080/customers
Content-Type: application/json

[
  {
    "name": "Test customer3"
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Put customers
PUT http://127.0.0.1:8080/customers
Content-Type: application/json

[
  {
    "id": 3,
    "name": "Test customer4",
    "orders": []
  },
  {
    "id": 1,
    "name": "put to customer1",
    "orders": []
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Get all Customers
GET http://127.0.0.1:8080/customers

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Patch multiple customers
PATCH http://127.0.0.1:8080/customers
Content-Type: application/json

[
  {
    "id": 3,
    "name": "customer3"
  },
  {
    "id": 1,
    "name": "customer1"
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Get single Customer
GET http://127.0.0.1:8080/customers/1

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Patch Customer
PATCH http://127.0.0.1:8080/customers/1
Content-Type: application/json

{
  "name": "Test customer1patched"
}

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Post multiple Products
POST http://127.0.0.1:8080/products
Content-Type: application/json

[
  {
    "title": "Product A",
    "price": 499
  },
  {
    "title": "Product B",
    "price": 1250
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Post single Product
POST http://127.0.0.1:8080/products
Content-Type: application/json

[
  {
    "title": "Product C",
    "price": 2500
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Put Multiple Products
PUT http://127.0.0.1:8080/products
Content-Type: application/json

[
  {
    "id": 3,
    "title": "Updated Product C",
    "price": 2700
  },
  {
    "id": 1,
    "title": "Updated Product A",
    "price": 450
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Get all Products
GET http://127.0.0.1:8080/products

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Get single Product
GET http://127.0.0.1:8080/products/1

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Patch Product
PATCH http://127.0.0.1:8080/products/1
Content-Type: application/json

{
  "title": "Patched Product B"
}

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Post single Order
POST http://127.0.0.1:8080/orders
Content-Type: application/json

[
  {
    "orderDate": "2026-07-09",
    "customer_id": 1
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Post multiple Orders
POST http://127.0.0.1:8080/orders
Content-Type: application/json

[
  {
    "orderDate": "2026-07-10",
    "customer_id": 3
  },
  {
    "orderDate": "2026-07-11",
    "customer_id": 1
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Put multiple Orders
PUT http://127.0.0.1:8080/orders
Content-Type: application/json

[
  {
    "id": 1,
    "orderDate": "2026-07-08",
    "customer_id": 3,
    "positions": []
  },
  {
    "id": 3,
    "orderDate": "2026-08-08",
    "customer_id": 1,
    "positions": []
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Put single Order
PUT http://127.0.0.1:8080/orders/2
Content-Type: application/json

{
  "id": 2,
  "orderDate": "2026-03-05",
  "customer_id": 1,
  "positions": []
}

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Get all Orders
GET http://127.0.0.1:8080/orders

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Get single Order
GET http://127.0.0.1:8080/orders/2

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Patch multiple Orders
PATCH http://127.0.0.1:8080/orders
Content-Type: application/json

[
  {
    "id": 1,
    "customer_id": 1
  },
  {
    "id": 3,
    "customer_id": 3
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Patch Order
PATCH http://127.0.0.1:8080/orders/2
Content-Type: application/json

{
  "orderDate": "2026-07-06"
}

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Post single position
POST http://127.0.0.1:8080/orders/1/positions
Content-Type: application/json

[
  {
    "quantity": 2,
    "buyingPrice": 450,
    "product_id": 1
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Post multiple positions
POST http://127.0.0.1:8080/orders/1/positions
Content-Type: application/json

[
  {
    "quantity": 1,
    "buyingPrice": 1250,
    "product_id": 2
  },
  {
    "quantity": 5,
    "buyingPrice": 2500,
    "product_id": 3
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Put single positions
PUT http://127.0.0.1:8080/orders/1/positions/1
Content-Type: application/json

[
  {
    "id": 1,
    "quantity": 3,
    "buyingPrice": 440,
    "product_id": 1,
    "order_id": 1
  },
  {
    "id": 2,
    "quantity": 2,
    "buyingPrice": 1200,
    "product_id": 2,
    "order_id": 1
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Patch Positions
PATCH http://127.0.0.1:8080/orders/1/positions
Content-Type: application/json

[
  {
    "id": 1,
    "quantity": 4
  },
  {
    "id": 2,
    "buyingPrice": 1150
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Get all Positions for an Order
GET http://127.0.0.1:8080/orders/1/positions

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Delete Position
DELETE http://127.0.0.1:8080/orders/1/positions
Content-Type: application/json

[
  {
    "id": 1
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Delete multiple Products
DELETE http://127.0.0.1:8080/products
Content-Type: application/json

[
  {
    "id": 2
  },
  {
    "id": 3
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Delete Customer
DELETE http://127.0.0.1:8080/customers/1

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Delete Product
DELETE http://127.0.0.1:8080/products/1

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Delete Order 1
DELETE http://127.0.0.1:8080/orders/1

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}


### Delete Orders
DELETE http://127.0.0.1:8080/orders
Content-Type: application/json

[
  {
    "id": 2
  }
]

###
> {%
client.test("Status OK", function() {
  client.assert(response.status === 200, "Fehler");
});
%}
